### ISSUE TITLE
Problem running in Casper

### ISSUE THREAD

**Issue by patgmac** [pbowden-msft/Remove2011#1]
Casper reserves $1 $2 and $3, so we have to use $4 and up when passing parameters. Which tells me I need to change any $1 references in this script to $4 that pertain to where --Force is being passed. But there are a lot of $1's that are not arguments, so I'm having a hard time figuring out which exact instances of $1 to change.

**Comment by jhbush** [comment]
@patgmac did you ever resolve this issue?

**Comment by pbowden-msft** [comment]
I just uploaded v1.3, with the fix.
