### ISSUE TITLE
What's the point of dockutil?

### ISSUE THREAD

**Issue by quornicus** [pbowden-msft/Remove2011#10]
Dockutil simply errors out and does nothing; it has had no options or arguments passed to it apparently. The directions here: https://support.office.com/en-us/article/troubleshoot-office-2011-for-mac-issues-by-completely-uninstalling-before-you-reinstall-ba8d8d13-0015-4eea-b60b-7719c2cedd17 say to run it. If you look at that page, you'll note that the image associated with the section encouraging you to run dockutil ALSO shows the result of a script that did nothing ("Error processing options: no action was specified.").

**Comment by sander1** [comment]
It looks like `dockutil` is executed (with arguments) from within `Remove2011`, see https://github.com/pbowden-msft/Remove2011/blob/master/Remove2011#L365

**Comment by pbowden-msft** [comment]
@sander1 is correct. If Dockutil is present in the Remove2011 script folder, the script will leverage it to automatically remove 2011 app icons from the dock.
