### ISSUE TITLE
Used tool to remove 2011

### ISSUE THREAD

**Issue by malisaspivey** [pbowden-msft/Remove2011#2]
so I used your tool, it looked great to me the idiot and then I tried to open outlook 2016 and here is what I got, do you have any suggestions. Please see the error file for more details.
/Users/Malisa/Library/Containers/com.microsoft.Outlook/Data/Library/Logs

**Comment by pbowden-msft** [comment]
Did you see any other information in the dialog apart from "Please see the error file ...." ?

**Comment by malisaspivey** [comment]
no it won't let me

**Comment by malisaspivey** [comment]
What does this mean and how do I totally get rid of outlook to start fresh.  I can relink my accounts and all will be fine, it just won't let me open it at all

**Comment by malisaspivey** [comment]
No Sir,

I just wont let me open outlook at all.  I would like to be able to start
fresh but do not know how.

Malisa Spivey
Broker
(254) 495-7735 - Cell
(254) 523-4247 - fax
malisaspivey@gmail.com
www.KeyTheRightChoice.com
