### ISSUE TITLE
Stuck on Removing Package Receipts

### ISSUE THREAD

**Issue by ackerman76** [pbowden-msft/Remove2011#5]
Gets stuck here and never completes.

Thanks for the tool; I wish it worked -- sigh. MS....

**Comment by pbowden-msft** [comment]
Interesting. Removing the receipts is one of the last tasks that the tool performs. Can you send me the log file please to see if I can figure out why it's getting stuck? If you open Terminal, then type "cd $TMPDIR" you should then see a file called "Remove2011.log". Thanks.

**Comment by wifff** [comment]
Removed Mac Office 2011 on my MacBook Air.
It takes really some time to execute the "Removing Package Receipts" step.

You can watch the script working:
cd $TMPDIR
tail -f Remove2011.log

Maybe one should give a hint in the docs or the UI to be patient...

Thanks for this great script !

Best regards from Switzerland
Wolfgang

**Comment by pbowden-msft** [comment]
@wifff thanks! I added "This can take several minutes" to the Removing Package Receipts step.
