### ISSUE TITLE
Does not remove other apps from Office2011

### ISSUE THREAD

**Issue by WardsParadox** [pbowden-msft/Remove2011#9]
This tool does not remove:
* OpenXML converter
* Microsoft Communicator
* Microsoft Messenger

in addition, does not remove the Office2011 folder itself reliably.

**Comment by HenkPoley** [comment]
Microsoft Help Viewer might be another remaining program, or from an even older Office version:
```
/Library/Application Support/Microsoft/HV1.0/Microsoft Help Viewer.app
```

Same with Microsoft Remote Desktop Connection:

```
/Applications/Remote Desktop Connection.app
```

I believe Silverlight was also installed along some Office versions:

```
/Library/Application Support/Microsoft/Silverlight/
```

Found these when cleaning up a system's 32bit apps, for a macOS 10.15 Catalina update.

**Comment by HenkPoley** [comment]
Another remnant:

```
/Library/Application Support/Microsoft/Office Converter Support/
```

Found with:

```
mdfind "(kMDItemExecutableArchitectures == 'i386') && (kMDItemExecutableArchitectures != 'x86_64')"
```

**Comment by pbowden-msft** [comment]
Thanks @HenkPoley I'm adding these additions to v1.6 of the script.
